build:
  environment:
    php:
      version: 7.0.8
      ini:
        'date.timezone': 'Europe/Berlin'
  dependencies:
  tests:
    before:
      - composer install
    override:
      -
        command: ./vendor/bin/phpunit --coverage-clover=my-coverage-file
        coverage:
          file: my-coverage-file
          format: php-clover
filter:
    excluded_paths:
        - tests/*
